services:
  next-app:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - next-app
